#!/bin/sh
# SPDX-FileCopyrightText: 2026 Francesco Panarese
# SPDX-License-Identifier: GPL-3.0-only
# Regenerates the translation template and compiles the shipped catalogs.
set -e
cd "$(dirname "$0")/.."

DOMAIN=plasma_applet_org.kde.plasma.xmbdashboard

find contents -name "*.qml" | sort | xargs xgettext --from-code=UTF-8 -C \
    -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 -ktr:1 -ktranslate:1 \
    --package-name="$DOMAIN" -o "po/$DOMAIN.pot"

for po in po/*.po; do
    lang=$(basename "$po" .po)
    msgmerge --update --backup=none "$po" "po/$DOMAIN.pot"
    mkdir -p "contents/locale/$lang/LC_MESSAGES"
    msgfmt "$po" -o "contents/locale/$lang/LC_MESSAGES/$DOMAIN.mo"
done

# JS catalog for the in-widget language override.
python3 - <<'EOF'
import glob, json, os, re

def parse(path):
    entries, msgid, msgstr, cur = {}, None, None, None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line.startswith("msgid "):
            if msgid:
                entries[msgid] = msgstr or ""
            msgid, msgstr, cur = json.loads(line[6:]), None, "id"
        elif line.startswith("msgstr "):
            msgstr, cur = json.loads(line[7:]), "str"
        elif line.startswith('"'):
            if cur == "id":
                msgid += json.loads(line)
            elif cur == "str":
                msgstr += json.loads(line)
        elif not line:
            if msgid:
                entries[msgid] = msgstr or ""
            msgid, msgstr, cur = None, None, None
    if msgid:
        entries[msgid] = msgstr or ""
    entries.pop("", None)
    return {k: v for k, v in entries.items() if v}

langs, cats = ["en"], {}
for po in sorted(glob.glob("po/*.po")):
    lang = os.path.basename(po)[:-3]
    langs.append(lang)
    cats[lang] = parse(po)

with open("contents/ui/i18n-catalogs.js", "w", encoding="utf-8") as f:
    f.write("// SPDX-FileCopyrightText" + ": 2026 Francesco Panarese\n")
    f.write("// SPDX-License-Identifier" + ": GPL-3.0-only\n")
    f.write("// Generated by tools/build-i18n.sh from po/*.po - do not edit.\n")
    f.write(".pragma library\n")
    f.write("var languages = %s\n" % json.dumps(langs))
    f.write("var catalogs = %s\n" % json.dumps(cats, ensure_ascii=False, indent=1))
EOF
